AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance Creation Example with VPC

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"  # CIDR block for the VPC

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: "10.0.0.0/24"  # CIDR block for the subnet

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP traffic
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Allow SSH from anywhere
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Allow HTTP from anywhere

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro  # Instance type
      ImageId: ami-03f4878755434977f  # AMI ID (Amazon Machine Image)
      KeyName: studentpractice  # Key pair name for SSH access (replace with your own)
      SecurityGroupIds:
        - !Ref MySecurityGroup  # Reference to the security group created above
      SubnetId: !Ref MySubnet  # Reference to the subnet within the VPC
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install nginx1 -y
          systemctl start nginx
          systemctl enable nginx
